branch-defaults:
  reed:
    environment: pc-env
environment-defaults:
  pc-env:
    branch: reed
    repository: origin
global:
  application_name: project-chronicle
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
