branch-defaults:
  master:
    environment: project-chronicle-dev
environment-defaults:
  project-chronicle-dev:
    branch: null
    repository: null
global:
  application_name: project-chronicle
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 2.7 running
    on 64bit Amazon Linux/2.3.3
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
