# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_subject',
            new_name='question_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
