# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
    ]
