# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='perfect_answer',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
