# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_delete_greeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id_login',
        ),
    ]
