# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20160816_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='speech.Teacher'),
            preserve_default=False,
        ),
    ]
