# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20160727_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='bhairavmehta95@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=30),
            preserve_default=False,
        ),
    ]
