# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20170225_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryKeyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('point_value', models.IntegerField()),
                ('number_of_hits', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryKeyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('point_value', models.IntegerField()),
                ('number_of_hits', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_answered', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
