# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_question_perfect_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='perfect_answer',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
