# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_rawtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('previous', models.BooleanField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.PrimaryKeyword')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Question')),
            ],
        ),
    ]
