# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_keywordcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('point_value', models.IntegerField()),
                ('number_of_hits', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='primarykeyword',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='secondarykeyword',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='keywordcontext',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Keyword'),
        ),
        migrations.DeleteModel(
            name='PrimaryKeyword',
        ),
        migrations.DeleteModel(
            name='SecondaryKeyword',
        ),
    ]
