# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_auto_20160813_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='l_name',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user_id_login',
            field=models.IntegerField(default=0),
        ),
    ]
