# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_auto_20170330_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicprogress',
            old_name='user_id',
            new_name='student_id',
        ),
    ]
