# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_auto_20171110_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='hint',
            field=models.CharField(default='hint', max_length=500),
            preserve_default=False,
        ),
    ]
