# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_auto_20160802_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='num_enrollments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_user_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='percent_to_pass',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='topic',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
