# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_auto_20170407_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicprogress',
            name='progress_percent',
        ),
    ]
