# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_remove_topicprogress_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speech.Class'),
            preserve_default=False,
        ),
    ]
