# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0006_question_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('question_subject', models.CharField(max_length=100)),
            ],
        ),
    ]
