# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0007_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='question_text',
            field=models.CharField(default='hje;;', max_length=5000),
            preserve_default=False,
        ),
    ]
