# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0008_testing_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='question_text',
            field=models.CharField(max_length=50000),
        ),
    ]
